// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
    
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {  
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqznkvH2y93BYc3chD-ExV3MMFqkzvnc0',
    appId: '1:1088463950262:android:62ac05eec7c376a40a3117',
    messagingSenderId: '1088463950262',
    projectId: 'vehnicatelogin',
    storageBucket: 'vehnicatelogin.firebasestorage.app',
  );
}